# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 440))
        MainWindow.setMaximumSize(QtCore.QSize(400, 440))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.pushButton_calc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calc.setGeometry(QtCore.QRect(320, 410, 61, 21))
        self.pushButton_calc.setObjectName("pushButton_calc")
        self.groupBox_input = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_input.setGeometry(QtCore.QRect(10, 50, 381, 111))
        self.groupBox_input.setObjectName("groupBox_input")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_input)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_input = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_input.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_input.setHorizontalSpacing(100)
        self.gridLayout_input.setObjectName("gridLayout_input")
        self.inputLabel_tds = QtWidgets.QLabel(self.gridLayoutWidget)
        self.inputLabel_tds.setObjectName("inputLabel_tds")
        self.gridLayout_input.addWidget(self.inputLabel_tds, 2, 0, 1, 1)
        self.inputLabel_do = QtWidgets.QLabel(self.gridLayoutWidget)
        self.inputLabel_do.setObjectName("inputLabel_do")
        self.gridLayout_input.addWidget(self.inputLabel_do, 1, 0, 1, 1)
        self.doubleSpinBox_ph = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_ph.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_ph.setSizePolicy(sizePolicy)
        self.doubleSpinBox_ph.setWrapping(False)
        self.doubleSpinBox_ph.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_ph.setMaximum(14.0)
        self.doubleSpinBox_ph.setSingleStep(0.1)
        self.doubleSpinBox_ph.setObjectName("doubleSpinBox_ph")
        self.gridLayout_input.addWidget(self.doubleSpinBox_ph, 0, 1, 1, 1)
        self.doubleSpinBox_do = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_do.setMaximum(10.0)
        self.doubleSpinBox_do.setSingleStep(0.1)
        self.doubleSpinBox_do.setObjectName("doubleSpinBox_do")
        self.gridLayout_input.addWidget(self.doubleSpinBox_do, 1, 1, 1, 1)
        self.doubleSpinBox_tds = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_tds.setMaximum(300.0)
        self.doubleSpinBox_tds.setObjectName("doubleSpinBox_tds")
        self.gridLayout_input.addWidget(self.doubleSpinBox_tds, 2, 1, 1, 1)
        self.inputLabel_ph = QtWidgets.QLabel(self.gridLayoutWidget)
        self.inputLabel_ph.setObjectName("inputLabel_ph")
        self.gridLayout_input.addWidget(self.inputLabel_ph, 0, 0, 1, 1)
        self.groupBox_output = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_output.setGeometry(QtCore.QRect(10, 160, 381, 241))
        self.groupBox_output.setObjectName("groupBox_output")
        self.label_condition = QtWidgets.QLabel(self.groupBox_output)
        self.label_condition.setGeometry(QtCore.QRect(70, 200, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_condition.setFont(font)
        self.label_condition.setAlignment(QtCore.Qt.AlignCenter)
        self.label_condition.setObjectName("label_condition")
        self.label_output = QtWidgets.QLabel(self.groupBox_output)
        self.label_output.setGeometry(QtCore.QRect(0, 160, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_output.setFont(font)
        self.label_output.setAlignment(QtCore.Qt.AlignCenter)
        self.label_output.setObjectName("label_output")
        self.outputLabel_tds = QtWidgets.QLabel(self.groupBox_output)
        self.outputLabel_tds.setGeometry(QtCore.QRect(270, 20, 91, 18))
        self.outputLabel_tds.setObjectName("outputLabel_tds")
        self.outputLabel_do = QtWidgets.QLabel(self.groupBox_output)
        self.outputLabel_do.setGeometry(QtCore.QRect(170, 20, 71, 19))
        self.outputLabel_do.setObjectName("outputLabel_do")
        self.outputLabel_ph = QtWidgets.QLabel(self.groupBox_output)
        self.outputLabel_ph.setGeometry(QtCore.QRect(70, 20, 76, 18))
        self.outputLabel_ph.setObjectName("outputLabel_ph")
        self.memberLabel_ph_low = QtWidgets.QLabel(self.groupBox_output)
        self.memberLabel_ph_low.setGeometry(QtCore.QRect(90, 50, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memberLabel_ph_low.sizePolicy().hasHeightForWidth())
        self.memberLabel_ph_low.setSizePolicy(sizePolicy)
        self.memberLabel_ph_low.setAutoFillBackground(False)
        self.memberLabel_ph_low.setAlignment(QtCore.Qt.AlignCenter)
        self.memberLabel_ph_low.setObjectName("memberLabel_ph_low")
        self.memberLabel_ph_mid = QtWidgets.QLabel(self.groupBox_output)
        self.memberLabel_ph_mid.setGeometry(QtCore.QRect(90, 80, 41, 21))
        self.memberLabel_ph_mid.setAlignment(QtCore.Qt.AlignCenter)
        self.memberLabel_ph_mid.setObjectName("memberLabel_ph_mid")
        self.memberLabel_ph_high = QtWidgets.QLabel(self.groupBox_output)
        self.memberLabel_ph_high.setGeometry(QtCore.QRect(90, 110, 41, 20))
        self.memberLabel_ph_high.setAlignment(QtCore.Qt.AlignCenter)
        self.memberLabel_ph_high.setObjectName("memberLabel_ph_high")
        self.memberLabel_do_mid = QtWidgets.QLabel(self.groupBox_output)
        self.memberLabel_do_mid.setGeometry(QtCore.QRect(190, 80, 41, 21))
        self.memberLabel_do_mid.setAlignment(QtCore.Qt.AlignCenter)
        self.memberLabel_do_mid.setObjectName("memberLabel_do_mid")
        self.memberLabel_do_high = QtWidgets.QLabel(self.groupBox_output)
        self.memberLabel_do_high.setGeometry(QtCore.QRect(190, 110, 41, 20))
        self.memberLabel_do_high.setAlignment(QtCore.Qt.AlignCenter)
        self.memberLabel_do_high.setObjectName("memberLabel_do_high")
        self.memberLabel_do_low = QtWidgets.QLabel(self.groupBox_output)
        self.memberLabel_do_low.setGeometry(QtCore.QRect(190, 50, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memberLabel_do_low.sizePolicy().hasHeightForWidth())
        self.memberLabel_do_low.setSizePolicy(sizePolicy)
        self.memberLabel_do_low.setAutoFillBackground(False)
        self.memberLabel_do_low.setAlignment(QtCore.Qt.AlignCenter)
        self.memberLabel_do_low.setObjectName("memberLabel_do_low")
        self.memberLabel_tds_mid = QtWidgets.QLabel(self.groupBox_output)
        self.memberLabel_tds_mid.setGeometry(QtCore.QRect(290, 80, 41, 21))
        self.memberLabel_tds_mid.setAlignment(QtCore.Qt.AlignCenter)
        self.memberLabel_tds_mid.setObjectName("memberLabel_tds_mid")
        self.memberLabel_tds_high = QtWidgets.QLabel(self.groupBox_output)
        self.memberLabel_tds_high.setGeometry(QtCore.QRect(290, 110, 41, 20))
        self.memberLabel_tds_high.setAlignment(QtCore.Qt.AlignCenter)
        self.memberLabel_tds_high.setObjectName("memberLabel_tds_high")
        self.memberLabel_tds_low = QtWidgets.QLabel(self.groupBox_output)
        self.memberLabel_tds_low.setGeometry(QtCore.QRect(290, 50, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memberLabel_tds_low.sizePolicy().hasHeightForWidth())
        self.memberLabel_tds_low.setSizePolicy(sizePolicy)
        self.memberLabel_tds_low.setAutoFillBackground(False)
        self.memberLabel_tds_low.setAlignment(QtCore.Qt.AlignCenter)
        self.memberLabel_tds_low.setObjectName("memberLabel_tds_low")
        self.label_low = QtWidgets.QLabel(self.groupBox_output)
        self.label_low.setGeometry(QtCore.QRect(20, 50, 21, 16))
        self.label_low.setObjectName("label_low")
        self.label_mid = QtWidgets.QLabel(self.groupBox_output)
        self.label_mid.setGeometry(QtCore.QRect(20, 80, 21, 16))
        self.label_mid.setObjectName("label_mid")
        self.label_high = QtWidgets.QLabel(self.groupBox_output)
        self.label_high.setGeometry(QtCore.QRect(20, 110, 21, 16))
        self.label_high.setObjectName("label_high")
        self.pushButton_showgraph = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_showgraph.setGeometry(QtCore.QRect(230, 410, 75, 23))
        self.pushButton_showgraph.setObjectName("pushButton_showgraph")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Drinking Water Quality"))
        self.label_title.setText(_translate("MainWindow", "Drinking Water Quality Testing With Fuzzy Logic"))
        self.pushButton_calc.setText(_translate("MainWindow", "Calculate"))
        self.groupBox_input.setTitle(_translate("MainWindow", "Input"))
        self.inputLabel_tds.setText(_translate("MainWindow", "Input TDS Value (0-300)"))
        self.inputLabel_do.setText(_translate("MainWindow", "Input Dissolved Oxygen Value (0-10)"))
        self.inputLabel_ph.setText(_translate("MainWindow", "Input pH Value (0-14)"))
        self.groupBox_output.setTitle(_translate("MainWindow", "Output"))
        self.label_condition.setText(_translate("MainWindow", "0/100"))
        self.label_output.setText(_translate("MainWindow", "Your Drinking Water Quality"))
        self.outputLabel_tds.setText(_translate("MainWindow", "TDS Membership"))
        self.outputLabel_do.setText(_translate("MainWindow", "DO Membeship "))
        self.outputLabel_ph.setText(_translate("MainWindow", "pH Membership "))
        self.memberLabel_ph_low.setText(_translate("MainWindow", "0"))
        self.memberLabel_ph_mid.setText(_translate("MainWindow", "0"))
        self.memberLabel_ph_high.setText(_translate("MainWindow", "0"))
        self.memberLabel_do_mid.setText(_translate("MainWindow", "0"))
        self.memberLabel_do_high.setText(_translate("MainWindow", "0"))
        self.memberLabel_do_low.setText(_translate("MainWindow", "0"))
        self.memberLabel_tds_mid.setText(_translate("MainWindow", "0"))
        self.memberLabel_tds_high.setText(_translate("MainWindow", "0"))
        self.memberLabel_tds_low.setText(_translate("MainWindow", "0"))
        self.label_low.setText(_translate("MainWindow", "Low"))
        self.label_mid.setText(_translate("MainWindow", "Mid"))
        self.label_high.setText(_translate("MainWindow", "High"))
        self.pushButton_showgraph.setText(_translate("MainWindow", "Graph"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setStatusTip(_translate("MainWindow", "New File"))

